# Generated by Django 4.0.3 on 2022-03-21 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_tour_departure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departure',
            options={'ordering': ['id'], 'verbose_name': 'Отправления', 'verbose_name_plural': 'Отправления'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['title'], 'verbose_name': 'Туры', 'verbose_name_plural': 'Туры'},
        ),
        migrations.AlterField(
            model_name='departure',
            name='departure',
            field=models.CharField(max_length=50, verbose_name='Отпрвление'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='ru_departure',
            field=models.CharField(max_length=100, verbose_name='Отправление(на русском)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='country',
            field=models.CharField(max_length=15, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='tours.departure', verbose_name='Отправление'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='nights',
            field=models.PositiveSmallIntegerField(verbose_name='Дни'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='picture',
            field=models.URLField(max_length=300, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='stars',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Звезды'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
